version: '3.8'

services:
  blauhaunt:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOSTNAME: ${HOSTNAME:-example.com}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    restart: unless-stopped
